
name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "6.0.x" # SDK Version to use.
          source-url: https://nuget.pkg.github.com/<owner>/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the project
        run: |
          dotnet build --configuration Release Chirp.sln
        shell: bash

      - name: Create the package
        run: |
          dotnet pack --configuration Release Chirp.sln
        shell: bash

      - name: Publish the package to GitHub Packages
        run: |
          dotnet nuget push Chirp/bin/Release/*.nupkg --source https://nuget.pkg.github.com/<owner>/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
        shell: bash
