name: .NET

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build Chirp.sln --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Create OS-Specific Output Directory
        run: |
          mkdir -p output/${RUNNER_OS}
          echo "Contents of bin/Debug/net8.0:"
          ls -R bin/Debug/net8.0

      - name: Zip Build Output
        run: |
          echo "Contents of bin/Debug/net8.0:"
          ls -R bin/Debug/net8.0
          if [ $RUNNER_OS = 'Linux' ] || [ $RUNNER_OS = 'macOS' ]; then
            zip -r output/build-${RUNNER_OS}.zip bin/Debug/net8.0 || true
          elif [ $RUNNER_OS = 'Windows' ]; then
            powershell -Command "Compress-Archive -Path bin/Debug/net8.0 -DestinationPath output/build-${RUNNER_OS}.zip" || true
          fi
        shell: bash

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-output-${{ matrix.os }}
          path: output/build-${{ matrix.os }}.zip
