name: .NET

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build Chirp.sln --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Zip Build Output
        run: |
          mkdir -p output
          if [ $RUNNER_OS = 'Linux' ] || [ $RUNNER_OS = 'macOS' ]; then
            zip -r output/build-${RUNNER_OS}.zip bin/Debug/net8.0
          elif [ $RUNNER_OS = 'Windows' ]; then
            powershell -Command "Compress-Archive -Path bin/Debug/net8.0 -DestinationPath output/build-${RUNNER_OS}.zip"
          fi

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: output/

      - name: Upload Project Zip
        uses: actions/upload-artifact@v3
        with:
          name: project-zip
          path: ${{ github.event.repository.name }}.zip

  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/<owner>/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the project
        run: |
          dotnet build --configuration Release Chirp.sln
        shell: bash

      - name: Create the package
        run: |
          dotnet pack --configuration Release Chirp.sln
        shell: bash

      - name: Publish the package to GitHub Packages
        run: |
          dotnet nuget push Chirp/bin/Release/*.nupkg --source https://nuget.pkg.github.com/<owner>/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
        shell: bash
