name: Build and Test .NET Project

on:
  push:
    tags:
      - "v*" # Trigger the workflow on new version tags
  pull_request:
    branches: [$default-branch]
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.x"

      - name: Install dependencies
        run: dotnet
        run: dotnet add package xunit --version 2.9.1
        
      - name: Build
        run: dotnet build

      - name: Test with the dotnet CLI
        run: dotnet test