name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.x"

      - name: Install dependencies
        run: |
          dotnet restore ./src/Chirp.Razor/Chirp.Razor.csproj
          dotnet restore ./test/ChirpRazor.Tests/ChirpRazor.Tests.csproj
          dotnet add ./test/ChirpRazor.Tests/ChirpRazor.Tests.csproj package xunit --version 2.9.2

      - name: dotnet test
        run: dotnet test ./test/ChirpRazor.Tests/ChirpRazor.Tests.csproj
