name: Build and Test .NET Project

on:
  push:
    tags:
      - "v*" # Trigger the workflow on new version tags
  pull_request:
    branches: [$default-branch]
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.x"

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build Chirp.sln --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal